### ISSUE TITLE
[Internal] Update Contact Information

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/survival-guide#14]
# Overview of Proposed Changes
There are some issues throughout the repo where we reference [nebula.acmutd.co](https://nebula.acmutd.co), the ACM discord server, and the nebula-maintainers@acmutd.co email among other things. Please examine the codebase for all locations where we reference outdated information and update it.

# Details
Please update these outdated values among others you may notice:
- nebula-maintainers@acmutd.co -> core-maintainers@utdnebula.com
- ACM Discord references can be replaced with core-maintainers@utdnebula.com

# Implementation
Please prioritize updating documentation files such as README and CONTRIBUTING as soon as possible

**Comment by WillieCubed** [comment]
Closing as stale (has been implemented in `develop`).
