### ISSUE TITLE
[Feature Request] Result Cards

### ISSUE THREAD

**Issue by ryan-radloff** [UTDNebula/survival-guide#22]
# Overview
Describe the motivation behind your desired functionality.

When a user searches a question, we want a list of articles to be returned on the results page. Each of the articles will be shown as a result card, which will contain (for now) the title of the article and a description.

How would you like the user experience for this feature to work?

When a search is made, an api call will fetch the title and description for the n most relevant articles. The frontend will parse the returned json and feed the title and description to the card element.

# Proposal
Describe what changes need to be implemented to resolve this issue. Be as
detailed as possible so maintainers can best determine how to implement this
new feature.

A component should be added to the project (tsx) so it can be dynamically created and placed in a grid upon search.

## Supplementary Information
To give your feature more chance at being implemented, feel free to attach any
other documentation. For something highly-user facing, a UI mock-up or some
other form of wireframe is required.

https://utdguide.atlassian.net/l/c/U9uR1q0D

**Comment by WillieCubed** [comment]
Closing as stale
