### ISSUE TITLE
[Feature Request] Homepage- Site Title

### ISSUE THREAD

**Issue by AvengingPrime** [UTDNebula/survival-guide#48]
# Overview
Provide a place for the site's title and short description of the purpose of the site, as well as a relevant image to represent the site

# Proposal
Implement components and import images relevant to the Site's Title section

## Supplementary Information
![image](https://user-images.githubusercontent.com/32879528/204115448-44a9489a-b08a-4ee4-9f90-a1c78bbbe4ad.png)

**Comment by legenung** [comment]
Design is changing this right now. We are thinking it will look much different from this. You might want to wait until our homepage design is 100% complete.

**Comment by WillieCubed** [comment]
Closed by #61
