### ISSUE TITLE
[Feature Request] Homepage UI - Announcements Section

### ISSUE THREAD

**Issue by VishvakBandi** [UTDNebula/survival-guide#7]
# Overview
Describe the motivation behind your desired functionality.

How would you like the user experience for this feature to work?

This component will give the user the ability to view recent announcements or important content pages. It will be situated to the right of the search component.

# Proposal
Add announcements component
Add cards that can display a scrollable list of other relevant articles

## Supplementary Information
![image](https://user-images.githubusercontent.com/22197767/139214901-caf62de9-7b40-4819-8368-ab1fe2db88a3.png)
  - Also found on the Project Nebula Figma

**Comment by WillieCubed** [comment]
Closing this as it's currently out of scope with the current iteration of the project.
